//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceRecognitionClient.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:recognitionwsdl", ConfigurationName="ServiceReference3.recognitionwsdlPortType")]
    public interface recognitionwsdlPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:recognitionwsdl#connectAndTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string uploadAndTest(string xmlfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:recognitionwsdl#udfRecognitionTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string udfRecognitionTest(string xmlfile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface recognitionwsdlPortTypeChannel : FaceRecognitionClient.ServiceReference3.recognitionwsdlPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class recognitionwsdlPortTypeClient : System.ServiceModel.ClientBase<FaceRecognitionClient.ServiceReference3.recognitionwsdlPortType>, FaceRecognitionClient.ServiceReference3.recognitionwsdlPortType {
        
        public recognitionwsdlPortTypeClient() {
        }
        
        public recognitionwsdlPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public recognitionwsdlPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public recognitionwsdlPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public recognitionwsdlPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string uploadAndTest(string xmlfile) {
            return base.Channel.uploadAndTest(xmlfile);
        }
        
        public string udfRecognitionTest(string xmlfile) {
            return base.Channel.udfRecognitionTest(xmlfile);
        }
    }
}
